# Generated by Django 6.1 on 2026-08-25 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integraciones', '0001_initial'),
        ('rat', '0001_initial'),
        ('titulares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaPrivacidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20, unique=True)),
                ('texto', models.TextField()),
                ('hash_sha256', models.CharField(editable=False, max_length=64)),
                ('vigente', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Política de privacidad',
                'verbose_name_plural': 'Políticas de privacidad',
            },
        ),
        migrations.CreateModel(
            name='RegistroConsentimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('OTORGADO', 'Otorgado'), ('REVOCADO', 'Revocado')], default='OTORGADO', max_length=10)),
                ('canal_origen', models.CharField(blank=True, help_text='URL o canal donde se otorgó.', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_otorgamiento', models.DateTimeField(auto_now_add=True)),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos', to='rat.actividadtratamiento')),
                ('integracion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_registrados', to='integraciones.sistemaintegrado')),
                ('politica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='consentimiento.politicaprivacidad')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='titulares.titular')),
            ],
            options={
                'verbose_name': 'Registro de consentimiento',
                'verbose_name_plural': 'Registros de consentimiento',
                'indexes': [models.Index(fields=['titular', 'actividad'], name='consentimie_titular_d2ea72_idx')],
            },
        ),
    ]
