# Generated by Django 6.1 on 2026-08-25 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integraciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut_hash', models.CharField(db_index=True, editable=False, help_text='SHA-256 del RUT normalizado, para ubicar al titular sin desencriptar.', max_length=64, unique=True)),
                ('rut_cifrado', models.TextField(blank=True, editable=False, help_text='RUT cifrado con AES-256-GCM (core.crypto). Usar la propiedad `rut`, no este campo directamente.')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('tipo_titular', models.CharField(choices=[('EMPLEADO', 'Empleado'), ('CLIENTE', 'Cliente'), ('CANDIDATO', 'Candidato'), ('PROVEEDOR', 'Proveedor'), ('MENOR_EDAD', 'Menor de edad (NNA)')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('integracion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulares_creados', to='integraciones.sistemaintegrado')),
            ],
            options={
                'verbose_name': 'Titular de datos',
                'verbose_name_plural': 'Titulares de datos',
            },
        ),
    ]
