# Generated by Django 6.1 on 2026-08-25 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titulares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudArco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_derecho', models.CharField(choices=[('ACCESO', 'Acceso'), ('RECTIFICACION', 'Rectificación'), ('SUPRESION', 'Supresión'), ('OPOSICION', 'Oposición'), ('PORTABILIDAD', 'Portabilidad'), ('BLOQUEO', 'Bloqueo temporal')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('RESUELTA', 'Resuelta'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('canal_ingreso', models.CharField(blank=True, max_length=100)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(editable=False, help_text='Calculada automáticamente: fecha_solicitud + 30 días corridos (Art. 11).')),
                ('fecha_prorroga', models.DateTimeField(blank=True, help_text='Solo si se notificó prórroga antes del vencimiento original.', null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('justificacion_rechazo', models.TextField(blank=True)),
                ('archivo_respaldo', models.FileField(blank=True, null=True, upload_to='arco_respaldos/%Y/%m/')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_arco', to='titulares.titular')),
            ],
            options={
                'verbose_name': 'Solicitud ARCO',
                'verbose_name_plural': 'Solicitudes ARCO',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
