# Generated by Django 6.1 on 2026-08-25 21:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('rubro', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('dpd_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Delegado de Protección de Datos')),
                ('dpd_contacto', models.CharField(blank=True, max_length=255, verbose_name='Contacto del DPD (email o teléfono)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organización',
            },
        ),
    ]
