# Generated by Django 6.1 on 2026-08-25 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaIntegrado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('api_key_hash', models.CharField(editable=False, help_text='SHA-256 de la API key. La key en texto plano nunca se persiste; ver crear_con_api_key().', max_length=64, unique=True)),
                ('scopes', models.JSONField(blank=True, default=list, help_text='Lista de endpoints/acciones permitidas a este sistema.')),
                ('contacto_tecnico', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('REVOCADO', 'Revocado')], default='ACTIVO', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sistema integrado',
                'verbose_name_plural': 'Sistemas integrados',
            },
        ),
        migrations.CreateModel(
            name='ContratoEncargado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.FileField(upload_to='contratos_encargado/%Y/%m/')),
                ('fecha_firma', models.DateField()),
                ('vigente', models.BooleanField(default=True)),
                ('sistema_integrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_encargado', to='integraciones.sistemaintegrado')),
            ],
            options={
                'verbose_name': 'Contrato de encargado',
                'verbose_name_plural': 'Contratos de encargado',
            },
        ),
        migrations.CreateModel(
            name='WebhookSuscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_destino', models.URLField()),
                ('eventos_suscritos', models.JSONField(default=list, help_text="Subconjunto de: ['PURGA_EJECUTADA', 'ARCO_RESUELTA', 'CONSENTIMIENTO_REVOCADO']")),
                ('secreto_cifrado', models.TextField(editable=False, help_text='Secreto HMAC cifrado (AES-256-GCM). Usar generar_secreto()/secreto.')),
                ('activo', models.BooleanField(default=True)),
                ('sistema_integrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='integraciones.sistemaintegrado')),
            ],
            options={
                'verbose_name': 'Suscripción a webhook',
                'verbose_name_plural': 'Suscripciones a webhook',
            },
        ),
        migrations.CreateModel(
            name='WebhookEntrega',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('entregado', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='integraciones.webhooksuscripcion')),
            ],
            options={
                'verbose_name': 'Entrega de webhook',
                'verbose_name_plural': 'Entregas de webhook',
                'ordering': ['-timestamp'],
            },
        ),
    ]
