# Generated by Django 6.1 on 2026-08-25 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_entidad', models.CharField(max_length=255)),
                ('tipo_destinatario', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO_NACIONAL', 'Externo nacional'), ('EXTERNO_INTERNACIONAL', 'Externo internacional')], max_length=30)),
                ('pais_ubicacion', models.CharField(blank=True, max_length=100)),
                ('es_encargado_tratamiento', models.BooleanField(default=False, help_text='Marca si procesa datos por cuenta de la organización (Art. 15 bis) y por tanto requiere un ContratoEncargado.')),
            ],
            options={
                'verbose_name': 'Destinatario',
                'verbose_name_plural': 'Destinatarios',
            },
        ),
        migrations.CreateModel(
            name='MedidaSeguridad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo_medida', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Medida de seguridad',
                'verbose_name_plural': 'Medidas de seguridad',
            },
        ),
        migrations.CreateModel(
            name='PlantillaProceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('base_licitud_sugerida', models.CharField(choices=[('CONSENTIMIENTO', 'Consentimiento (Art. 12)'), ('CONTRATO', 'Ejecución contractual (Art. 13 letra c)'), ('OBLIGACION_LEGAL', 'Obligación legal (Art. 13 letra b)'), ('INTERES_LEGITIMO', 'Interés legítimo (Art. 13 letra d)'), ('DEFENSA_DERECHOS', 'Defensa de derechos (Art. 13 letra e)'), ('DATOS_ECONOMICOS', 'Datos económicos/comerciales (Art. 13 letra a)')], max_length=30)),
                ('plazo_sugerido_meses', models.PositiveIntegerField(blank=True, null=True)),
                ('campos_tipicos', models.JSONField(blank=True, default=list, help_text='Lista de nombres de TipoDato típicos de este proceso.')),
            ],
            options={
                'verbose_name': 'Plantilla de proceso',
                'verbose_name_plural': 'Plantillas de proceso',
            },
        ),
        migrations.CreateModel(
            name='TipoDato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100, unique=True)),
                ('es_sensible', models.BooleanField(default=False, help_text='Datos sensibles conforme Art. 2 letra g (ver SKL-LEGAL-002).')),
                ('es_biometrico', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de dato',
                'verbose_name_plural': 'Tipos de dato',
            },
        ),
        migrations.CreateModel(
            name='ActividadTratamiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('finalidad', models.TextField()),
                ('base_licitud', models.CharField(choices=[('CONSENTIMIENTO', 'Consentimiento (Art. 12)'), ('CONTRATO', 'Ejecución contractual (Art. 13 letra c)'), ('OBLIGACION_LEGAL', 'Obligación legal (Art. 13 letra b)'), ('INTERES_LEGITIMO', 'Interés legítimo (Art. 13 letra d)'), ('DEFENSA_DERECHOS', 'Defensa de derechos (Art. 13 letra e)'), ('DATOS_ECONOMICOS', 'Datos económicos/comerciales (Art. 13 letra a)')], max_length=30)),
                ('plazo_conservacion_meses', models.PositiveIntegerField(help_text='Vencido este plazo, el motor de retención anonimiza o elimina (módulo apps.auditoria).')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destinatarios', models.ManyToManyField(blank=True, related_name='actividades', to='rat.destinatario')),
                ('medidas_seguridad', models.ManyToManyField(blank=True, related_name='actividades', to='rat.medidaseguridad')),
                ('plantilla_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='rat.plantillaproceso')),
                ('tipos_dato', models.ManyToManyField(blank=True, related_name='actividades', to='rat.tipodato')),
            ],
            options={
                'verbose_name': 'Actividad de tratamiento',
                'verbose_name_plural': 'Actividades de tratamiento',
            },
        ),
    ]
