# Generated by Django 6.1 on 2026-08-25 21:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integraciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modulo', models.CharField(max_length=50)),
                ('accion', models.CharField(choices=[('ACCESO', 'Acceso'), ('MODIFICACION', 'Modificación'), ('EXPORTACION', 'Exportación'), ('PURGA', 'Purga / eliminación'), ('ANONIMIZACION', 'Anonimización')], max_length=20)),
                ('descripcion', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('hash_registro', models.CharField(editable=False, max_length=64)),
                ('integracion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditadas', to='integraciones.sistemaintegrado')),
                ('usuario', models.ForeignKey(blank=True, help_text='Nulo si la acción provino de una integración externa (ver integracion_origen).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
